[package]
name = "cglsys"
version = "0.1.0"
authors = ["Thor Correia <thor.lucas@icloud.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/thorlucas/cglsys"

[dependencies]
cgmath = "0.17.0"
cglsys-macro = { path = "lib/cglsys-macro/" }
